#from ..database import db
#from app.extensions import db
from extensions import db

from sqlalchemy import Table, Column, Integer, Text, Date, Boolean, String, ForeignKey
from sqlalchemy import create_engine, Column, Integer, BigInteger, Text, Date, Boolean, String, MetaData, Table

"""
class Item(db.Model):
    __tablename__ = 'items'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    user = db.relationship('User', backref=db.backref('items', lazy=True))
"""

class TDemande(db.Model):
    __tablename__ = 't_demande'
    idt_demande = Column(BigInteger, primary_key=True)
    #country = Column(String)
    #idt_demande = Column(BigInteger)
    no_interne = Column(String(9))
    date_de_depot = Column(Date)
    date_complet = Column(Date)
    code_avis = Column(String(1))
    id_commission = Column(Integer)
    date_limiteval = Column(Date)
    no_pacage_demandeur = Column(String(9))
    dem_autprof = Column(String(30))
    no_pacage_cedant = Column(String(9))
    jeune_agriculteur = Column(Integer)
    jeune_agr_aide = Column(Integer)
    code_motifcess = Column(Integer)
    type_demande = Column(Integer)
    cedantinforme = Column(Integer)
    uta_demandeur = Column(String(50))
    nb_salaries = Column(String(50))
    sau_demandeur = Column(String(50))
    smi = Column(String(2))
    demanter = Column(Integer)
    surface_demandee = Column(String(50))
    distance_siege = Column(String(50))
    distance_parcelle = Column(String(50))
    surface_unite_ref = Column(String(50))
    date_transfert = Column(Date)
    demanhs = Column(Integer)
    type_demande_hs = Column(Integer)
    natu_demande_hs = Column(Integer)
    effectifhs = Column(Integer)
    sau_ponderee_demandeur = Column(String(50))
    pad_demandeur = Column(String(50))
    date_signature_decision = Column(Date)
    motif_ctrl = Column(String(2))
    code_decision = Column(String(1))
    date_editdecis = Column(Date)
    optimclecomp_no_pa_id_co = Column(String(13))
    sau_cedant = Column(String(50))
    date_avis = Column(Date)
    code_statut = Column(String(1))
    motiv_c = Column(Text)
    motiv_d = Column(Text)
    motiv_a = Column(Text)
    motiv_p = Column(Text)
    sele_motictrl = Column(Integer)
    id_commissioncode_statut = Column(String(4))
    no_pacage_demandeurid_commission = Column(String(15))
    no_pacage_cedantno_interne = Column(String(20))
    id_commissioncode_statutno_pacage_cedant = Column(String(15))
    aj6mois = Column(String(1))
    env_giee = Column(Boolean)
    env_dephy = Column(Boolean)
    env_cert_maaf = Column(Boolean)
    env_cert_biopart = Column(Boolean)
    env_cert_biotot = Column(Boolean)
    distance_siege_proche = Column(String(50))
    distance_siege_eloigne = Column(String(50))
    rt_compens_utilpub = Column(Boolean)
    rt_compens_utilpub_surf = Column(String(50))
    rt_compens_rprop = Column(Boolean)
    rt_compens_rprop_surf = Column(Integer)
    rt_compens_autre = Column(Boolean)
    rt_compens_autre_surf = Column(String(50))
    rt_compens_autre_motif = Column(String(50))
    rt_deplanimaux = Column(Boolean)
    rt_deplanimaux_surf = Column(String(50))
    rt_echcedant = Column(Boolean)
    rt_echcedant_surf = Column(String(50))
    rt_bio = Column(Boolean)
    rt_bio_surf = Column(String(50))
    surf_rep_bio = Column(String(50))
    surf_rep_echange = Column(String(50))
    surf_rep_depanimaux = Column(Integer)
    reprise_dossier = Column(Boolean)
    date_limite_depot = Column(Date)
    nb_concurrences = Column(Integer)
    env_titre_sec = Column(Boolean)
    id_naturetransac = Column(Integer)
    instal3p = Column(Integer)
    instalstage = Column(Integer)
    instaletude = Column(Integer)
    cedantexpab = Column(Integer)
    cedantexpconv = Column(Integer)
    rt_compens_ind_surf = Column(Boolean)
    ide_globale = Column(String(50))
    surf_zsce = Column(String(50))
    id_redaction_decision = Column(Integer)
    total_ide = Column(String(50))
    id_gestionnaire = Column(Integer)
    demandebat = Column(Integer)
    saup = Column(String(50))
    dossiersuccessif = Column(Boolean)
    dossierconcurrentsuccessif = Column(Boolean)
    ideuta = Column(String(50))
    memodemandeur = Column(Text)
    memocedant = Column(Text)
    recours = Column(Boolean)
    daterecours = Column(Date)
    id_logics = Column(String(50))
    pideuta = Column(String(50))
    schema = Column(Integer)
    sempastous = Column(Boolean)
    date_sempastous = Column(Date)
    user_id = Column(Integer)


class TUsager(db.Model):
    __tablename__ = 't_usager'
    idt_usager = Column(BigInteger, primary_key=True)
    u_pacage = Column(String(9))
    u_civilite = Column(String(12))
    u_nom_raison_sociale = Column(String(40))
    u_prenoms = Column(String(30))
    u_forme_juridique = Column(String(50))
    u_siret = Column(String(14))
    u_msa = Column(String(14))
    u_etat = Column(String(10))
    u_date_debut_validite_sigc = Column(String(10))
    u_date_fin_validite_sigc = Column(String(10))
    u_date_cloture = Column(String(10))
    u_civilite_edit = Column(String(30))

